// Per-card mock data — substituted into Liquid placeholders for the review surface.
// Real campaign URLs from past Customer.io templates where possible; locally-generated
// gpt-image-2 infographics for fields where the Liquid placeholder doesn't resolve to
// a real CDN path (sparkline, dashboards, scorecards, etc).
//
// This is review-only mock data, not production. Real send-time rendering happens
// in Customer.io against actual customer profiles.

export type MockContext = Record<string, unknown>;

// Shared reference URLs — all verified 200 OK on the Customer.io CDN
const ASSETS = {
  packArt:
    "https://userimg-assets.customeriomail.com/images/client-env-161112/1747166167882_03-PACKS-ARE-YOUR-DOORWAY-TO-GREATNESSNEW2_01JV5KFXMNRPTA0J24ESESYX7N.jpg",
  setHero:
    "https://userimg-assets.customeriomail.com/images/client-env-161112/1733254430310_04-MORE-THAN-MOMENTS_01_01JE707FKDZM5GN3VEF7G26DYG.jpg",
  collectorFirstPack:
    "https://userimg-assets.customeriomail.com/images/client-env-161112/1740722955824_01-NEW-COLLECTOR-FIRST-PACK2_01JN5JRSMVBKXQ9YK4ESN8FFAS.jpg",
  packAnimated:
    "https://userimg-assets.customeriomail.com/images/client-env-161112/1734135875841_tier4_01JF18V2BX0TMRW39EA1J2FETP.gif",
  bottomBanner:
    "https://userimg-assets.customeriomail.com/images/client-env-161112/1734135959963_04-MORE-THAN-MOMENTS-bottom_01JF18XMG4SDNNGA4Q6Y9W91A4.jpg",
  winExperience:
    "https://userimg-assets.customeriomail.com/images/client-env-161112/1733248546287_01A-WIN-THE-ULTIMATE-FAN-EXPERIENCE_06_01JE6TKVN6TCK7F2VWH2RBAFBH.jpg",
  // Locally generated infographics in /public/cards/infographics/
  sparkline: "/cards/infographics/sparkline-holdings.png",
  marketDashboard: "/cards/infographics/market-dashboard-thumb.png",
  fastBreakScorecard: "/cards/infographics/fastbreak-scorecard.png",
  dropDatacard: "/cards/infographics/drop-datacard.png",
  whaleChart: "/cards/infographics/whale-chart.png",
  setcard: "/cards/infographics/setcard.png",
  momentPlaceholder: "/cards/infographics/moment-hero-placeholder.png",
  // Per-variant hero images (generated by frame-imagery swarm, 2026-05-04)
  reactivationCinematic: "/cards/infographics/reactivation-cinematic.png",
  reactivationAlmanac: "/cards/infographics/reactivation-almanac.png",
  reactivationBrief: "/cards/infographics/reactivation-brief.png",
  whaleCinematic: "/cards/infographics/whale-cinematic.png",
  whaleAlmanac: "/cards/infographics/whale-almanac.png",
  whaleBrief: "/cards/infographics/whale-brief.png",
  packAlmanac: "/cards/infographics/pack-received-almanac.png",
  packCinematic: "/cards/infographics/pack-received-cinematic.png",
  dropCinematic: "/cards/infographics/drop-cinematic.png",
  dropBrief: "/cards/infographics/drop-brief.png",
  fastBreakCinematic: "/cards/infographics/fast-break-cinematic.png",
  fastBreakBrief: "/cards/infographics/fast-break-brief.png",
  abandonedCartCinematic: "/cards/infographics/abandoned-cart-cinematic.png",
  abandonedCartBrief: "/cards/infographics/abandoned-cart-brief.png",
  welcomeCinematic: "/cards/infographics/welcome-cinematic.png",
};

// Default mock collector — used across most cards for cohesion
// DATA NOTE: notable_holdings_moving is grounded in real BQ marketplace data.
// Prices, serials, and sale dates are pulled from dapperlabs-data.production_mart_nba_product.mart_nba_product_marketplace.
// "Bought price" reflects the earliest documented secondary-market floor for that edition
// (i.e., the entry price available to a collector acquiring at or near drop).
// This collector represents the Segment A "Origin Story Holder" — bought S1 in 2020, has been dormant ~1,700d.
const SARAH: MockContext = {
  userName: "Sarah",
  first_session_at: "2020-10-28T10:00:00Z",  // S1 era
  last_session_days_ago: 1698,               // ~4.6 years dormant — pre-2022 era buyer
  lifetime_moments_owned: 94,
  lifetime_value: "$188,000",
  team_count_at_moment: 6,
  notable_holdings_moving: [
    {
      // Jokic S1 Holo MMXX Legendary — the anchor position
      // BQ: serial #14 last sold 2026-02-12 at $2,250; serial #5 sold 2026-05-01 at $2,555; serial #28 sold 2026-03-30 at $3,399
      // Entry price: S1 Holo MMXX floor in 2021 was ~$550-$899 for non-jersey serials
      player: "Nikola Jokić",
      set: "Series 1 — Holo MMXX",
      serial: "14",
      bought_at: "2021-03-10T14:00:00Z",
      bought_price: "$650",
      floor_today: "$2,250",
      recent_comp: "$3,399",
      recent_comp_at: "2026-03-30T21:11:07Z",
      pct_change: "+246%",
      image_url:
        "https://userimg-assets.customeriomail.com/images/client-env-161112/1747166167882_03-PACKS-ARE-YOUR-DOORWAY-TO-GREATNESSNEW2_01JV5KFXMNRPTA0J24ESESYX7N.jpg",
    },
    {
      // LeBron S1 Cosmic Legendary — the highest-value position
      // BQ: serial #41 sold 2026-03-09 at $13,000; serial #44 sold 2026-01-04 at $12,750
      // Entry price: 2021 era median was ~$3,750-$5,000 for mid-range serials
      player: "LeBron James",
      set: "Series 1 — Cosmic",
      serial: "41",
      bought_at: "2021-04-22T18:00:00Z",
      bought_price: "$3,750",
      floor_today: "$12,750",
      recent_comp: "$13,000",
      recent_comp_at: "2026-03-09T05:50:07Z",
      pct_change: "+240%",
      image_url: ASSETS.setHero,
    },
    {
      // Victor Wembanyama Constellations Series 7 Rare — the "recent add" position
      // BQ: serial #138 sold 2026-05-01 at $43; serial #11 (premium jersey adjacent) sold at $77
      // Drop floor Feb 19, 2026: $27 for non-jersey Wemby serials
      player: "Victor Wembanyama",
      set: "Series 7 — Constellations",
      serial: "138",
      bought_at: "2026-02-19T10:00:00Z",
      bought_price: "$27",
      floor_today: "$43",
      recent_comp: "$77",
      recent_comp_at: "2026-05-01T23:44:45Z",
      pct_change: "+59%",
      image_url: ASSETS.collectorFirstPack,
    },
  ],
  holdings_sparkline_url: ASSETS.sparkline,
};

// "DO NOT SEND" comparison profile — collector whose portfolio is deeply underwater.
// Represents the 2022 ATH-era buyer (Segment: S3/S4 era, ~480 collectors in cohort).
// BQ data: Giannis 2021 Finals Legendary median sale price in 2021 was $5,900; current floor $650 (single 2026 sale).
// LeBron S2 Holo Icon: 2021 median $19,999; current floor $777.
// DO NOT send "wallet is up" copy to this cohort — factually false, destroys trust.
// Use a different reactivation angle (documentary value, not financial appreciation).
const KAI_FLAT: MockContext = {
  userName: "Kai",
  first_session_at: "2021-12-08T10:00:00Z",   // Joined at ATH, bought Legendaries at peak
  last_session_days_ago: 1402,                  // Dormant since mid-2022
  lifetime_moments_owned: 178,
  lifetime_value: "$195,000",
  team_count_at_moment: 5,
  // NEGATIVE MATH — do not use for "wallet is up" framing
  notable_holdings_moving: [
    {
      // Giannis S2 2021 NBA Finals Legendary — bought at peak, DOWN 89%
      // BQ: 2021 median sale $5,900; 2026 latest sale $650
      player: "Giannis Antetokounmpo",
      set: "Series 2 — 2021 NBA Finals",
      serial: "82",
      bought_at: "2022-01-15T14:00:00Z",
      bought_price: "$5,900",
      floor_today: "$650",
      recent_comp: "$650",
      recent_comp_at: "2026-03-27T00:06:36Z",
      pct_change: "-89%",
      image_url: ASSETS.setHero,
    },
    {
      // LeBron S2 Holo Icon Legendary — bought at ATH, DOWN 96% from peak
      // BQ: 2021 median $19,999; 2026 floor $777 (one sale)
      player: "LeBron James",
      set: "Series 2 — Deck the Hoops",
      serial: "47",
      bought_at: "2022-01-20T18:00:00Z",
      bought_price: "$12,500",
      floor_today: "$777",
      recent_comp: "$2,300",
      recent_comp_at: "2026-04-12T05:30:41Z",
      pct_change: "-94%",
      image_url: ASSETS.momentPlaceholder,
    },
    {
      // Luka S2 Holo Icon Legendary — bought at ATH, DOWN 92%
      // BQ: 2021 median $7,500; 2026 single sale $625
      player: "Luka Dončić",
      set: "Series 2 — Holo Icon",
      serial: "63",
      bought_at: "2022-01-25T20:00:00Z",
      bought_price: "$7,500",
      floor_today: "$625",
      recent_comp: "$625",
      recent_comp_at: "2026-01-27T06:02:45Z",
      pct_change: "-92%",
      image_url: ASSETS.momentPlaceholder,
    },
  ],
  holdings_sparkline_url: ASSETS.sparkline,
  _do_not_send_note:
    "DO NOT use KAI_FLAT for 'wallet is up' reactivation copy. This collector is deeply underwater. Estimated cohort: ~480 collectors who last transacted in 2022-2023 at ATH prices. Different message needed (documentary value frame, not appreciation frame).",
};

const MARCUS_WHALE: MockContext = {
  userName: "Marcus",
  lifetime_moments_owned: 312,
  lifetime_value: "$147,200",
  lifetime_stage: "L4",
  first_session_at: "2020-10-22T18:00:00Z",
  portfolio_7d_change: "+4.2%",
  portfolio_positions_moved: "27",
  whale_chart_image_url: ASSETS.whaleChart,
};

const WEEK: MockContext = {
  featured_games:
    "Knicks/76ers · Cavs/Pacers · Thunder/Lakers · Spurs/Wolves",
};

const MARKET: MockContext = {
  recent_drop_velocity: "$1.2M cleared in T-30",
  weekly_sales_count: "47,820",
  weekly_median_price: "$64",
  active_set_count: "23",
  new_drops_this_week: "5",
  serial_max: "65,000",
  dashboard_image_url: ASSETS.marketDashboard,
};

// ===================================================================
// Per-card mock contexts. Keys match card IDs in lib/cards.ts.
// ===================================================================

export const MOCK_CONTEXTS: Record<string, MockContext> = {
  // REACTIVATION DRIP — targets positive-math dormant L+XL collectors.
  // SARAH = Origin Story Holder (Segment A). Pre-2022 buyer, S1 Legendaries up 240-246%.
  // Use SARAH (positive math). Do NOT use KAI_FLAT (deeply underwater, see note on that const).
  // Estimated positive-math send cohort from BQ: ~350-550 of the 1,164 dormant L+XL collectors.
  // Source: dapperlabs-data.production_mart_nba_product.mart_nba_product_marketplace (queried 2026-05-04).
  "reactivation-drip": {
    customer: SARAH,
    week: WEEK,
    market: MARKET,
  },
  // Comparison — would NOT send this variant (negative math, 2022 ATH buyers):
  // "reactivation-drip-do-not-send": { customer: KAI_FLAT, week: WEEK, market: MARKET },

  "pack-received-voice": {
    customer: SARAH,
    event: {
      packTitle: "Cooper Flagg Rookie Debut Pack",
      quantity: 1,
      packImageURL: ASSETS.packAnimated,
      setName: "Rookie Debut",
      setTier: "Rare",
      setMomentCount: "12",
      setCirculation: "8,500",
      set_marquee_player: "Cooper Flagg",
      set_chronicler_note:
        "the first postseason of the most-anticipated rookie since LeBron",
      set_curator_name: "Guy",
      setFlowID: "rookie-debut-2026",
      set_7d_volume_count: "2,420",
      set_7d_median_price: "$185",
      set_floor_today: "$72",
      set_floor_change_7d: "+18%",
      setcard_image_url: ASSETS.setcard,
      set_top_3_recent_sales: [
        {
          player: "Cooper Flagg",
          play: "Three-Pointer · Q4",
          amount: "$1,247",
          sold_at: "2026-05-03T20:15:00Z",
        },
        {
          player: "Cooper Flagg",
          play: "Block · Q2",
          amount: "$892",
          sold_at: "2026-05-03T18:42:00Z",
        },
        {
          player: "Cooper Flagg",
          play: "Steal · Q3",
          amount: "$634",
          sold_at: "2026-05-03T17:08:00Z",
        },
      ],
    },
  },

  "welcome-onboarding": {
    customer: { ...SARAH, userName: "Alex", lifetime_moments_owned: 0 },
    week: WEEK,
    market: MARKET,
  },

  "fast-break-result-fix": {
    customer: { ...SARAH, fastbreak_win_streak: 3, fastbreak_lifetime_wins: 12 },
    event: {
      lineupPlayers: "SGA · Edwards · Mobley · Brunson · Bane",
      lineupSummary: "Defensive-anchor build, mid-tier scorers",
      totalScore: "147",
      gameCount: "4",
      winRank: "Top 8%",
      fastBreakId: "fb-2026-05-03",
      claim_expires_at: "2026-05-04T23:59:00Z",
      scorecard_image_url: ASSETS.fastBreakScorecard,
    },
  },

  "drop-announcement-programmatic": {
    drop: {
      id: "series-9-flagg",
      name: "Series 9 — Cooper Flagg Rookie Edition",
      set_name: "The Rookie Era",
      tier: "Premium",
      circulation_total: "8,500",
      moment_count: "15",
      starting_price: "$25",
      live_at: "2026-05-08T20:00:00Z",
      queue_open_at: "2026-05-08T19:30:00Z",
      featured_player_marquee: "Cooper Flagg · #1 overall pick",
      featured_player_legend:
        "First Duke player to go #1 since Zion. Pre-draft consensus called him the most complete prospect since LeBron. The set documents his rookie season as it happens — 15 Moments, 8,500 mints, one chance.",
      curator_note:
        "captures Cooper Flagg's rookie postseason — minted as it happens, sealed by the buzzer. The set every collector who came in 2026 will be measured against five years from now.",
      curator_name: "Guy",
      expected_serial_distribution: "Most packs will land in the 2,500-7,500 serial band; #1-#100 reserved for top-tier rewards.",
      previous_comparable: {
        set_name: "Series 8 Wembanyama",
        sellout_minutes: "11",
        floor_today: "$148",
      },
      serial_max: "8,500",
      likely_first_movers: "Whale collectors, Cooper Flagg-set completists",
      datacard_image_url: ASSETS.dropDatacard,
      hero_image: "/cards/infographics/drop-cinematic.png",
    },
    market: MARKET,
  },

  "abandoned-cart": {
    customer: SARAH,
    event: {
      player: "Donovan Mitchell",
      playCategory: "Pull-Up Three",
      setName: "Eastern Conference Run",
      tier: "Rare",
      circulationCount: "3,500",
      setMomentCount: "8",
      momentFlowID: "mitchell-pullup-2026",
      moment_image_url: ASSETS.collectorFirstPack,
      teamAtMoment: "Cleveland Cavaliers",
      serial: "2,418",
      listing_price: "$245",
      set_chronicler_note:
        "Eastern Conference Run captures Cleveland's Round 2 push — when Mitchell turned the corner from regular-season scorer to playoff closer.",
      recent_serial_band_sales: [
        {
          serial_range: "2,400-2,500",
          amount: "$312",
          sold_at: "2026-05-03T16:00:00Z",
        },
        {
          serial_range: "2,500-2,700",
          amount: "$287",
          sold_at: "2026-05-02T22:30:00Z",
        },
        {
          serial_range: "2,200-2,400",
          amount: "$298",
          sold_at: "2026-05-01T19:15:00Z",
        },
      ],
    },
  },

  "whale-tier-concierge": {
    customer: { ...MARCUS_WHALE, id: "marcus-vance-l4" },
    whale: {
      pattern_1: {
        title: "Cooper Flagg pre-draft accumulation",
        body: "Three L5 collectors quietly built positions in pre-rookie Flagg Moments over the last 14 days; floor moved 18% with low volume",
        player_concentration: "Cooper Flagg",
        cohort_size: "3 L5",
        recent_comp: "$485",
        market_signal: "+18% floor on <30 transactions",
      },
      pattern_2: {
        title: "Eastern Conference Run set tightening",
        body: "Mitchell + Mobley sub-3,000 serials are tightening fast — comparable serial bands cleared 30% above floor in last 72h",
        player_concentration: "Mitchell, Mobley",
        cohort_size: "Sub-3K serial band",
        recent_comp: "$312",
        market_signal: "Bid-ask spread halved in 72h",
      },
      pattern_3: {
        title: "Series 8 Wembanyama floor consolidation",
        body: "The Wembanyama Series 8 floor has stabilized at $148 after three months of slow decline — first sign of bottom-fishing",
        player_concentration: "Wembanyama",
        cohort_size: "All Series 8 holders",
        recent_comp: "$148",
        market_signal: "Floor flat 14d, bid-ask narrowing",
      },
      hold_recommendation: {
        player: "Donovan Mitchell",
        set: "Pull-Up Three",
        serial: "2,418",
        bought_at: "2024-01-20T20:30:00Z",
        bought_price: "$112",
        floor_today: "$245",
      },
    },
  },
};
